"""empty message

Revision ID: 1ea89a2e2d5a
Revises: 342f51d0dfd0
Create Date: 2019-08-28 23:40:48.591816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ea89a2e2d5a'
down_revision = '342f51d0dfd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('os_information', sa.Column('and32_64', sa.String(length=100), nullable=True))
    op.add_column('os_information', sa.Column('cpu', sa.String(length=100), nullable=True))
    op.add_column('os_information', sa.Column('cpu_rate', sa.String(length=100), nullable=True))
    op.add_column('os_information', sa.Column('disk', sa.String(length=100), nullable=True))
    op.add_column('os_information', sa.Column('information', sa.String(length=100), nullable=True))
    op.add_column('os_information', sa.Column('memory', sa.String(length=100), nullable=True))
    op.add_column('os_information', sa.Column('pci', sa.String(length=100), nullable=True))
    op.add_column('os_information', sa.Column('tableState', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('os_information', 'tableState')
    op.drop_column('os_information', 'pci')
    op.drop_column('os_information', 'memory')
    op.drop_column('os_information', 'information')
    op.drop_column('os_information', 'disk')
    op.drop_column('os_information', 'cpu_rate')
    op.drop_column('os_information', 'cpu')
    op.drop_column('os_information', 'and32_64')
    # ### end Alembic commands ###
