"""empty message

Revision ID: 342f51d0dfd0
Revises: b20f736656ed
Create Date: 2019-08-28 20:48:57.883529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '342f51d0dfd0'
down_revision = 'b20f736656ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('os_information', sa.Column('ip', sa.String(length=100), nullable=False))
    op.add_column('os_information', sa.Column('name', sa.String(length=100), nullable=False))
    op.drop_column('os_information', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('os_information', sa.Column('username', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('os_information', 'name')
    op.drop_column('os_information', 'ip')
    # ### end Alembic commands ###
