"""empty message

Revision ID: cd5614a48fe9
Revises: 1ea89a2e2d5a
Create Date: 2019-08-28 23:52:00.316625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd5614a48fe9'
down_revision = '1ea89a2e2d5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('os_information', sa.Column('username', sa.String(length=100), nullable=False))
    op.drop_column('os_information', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('os_information', sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('os_information', 'username')
    # ### end Alembic commands ###
