"""empty message

Revision ID: 4bfc64d760e1
Revises: 
Create Date: 2019-09-03 19:18:48.155031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bfc64d760e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('os_information',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('cpu', sa.String(length=100), nullable=True),
    sa.Column('memory', sa.String(length=100), nullable=True),
    sa.Column('disk', sa.String(length=100), nullable=True),
    sa.Column('cpu_rate', sa.String(length=100), nullable=True),
    sa.Column('and32_64', sa.String(length=100), nullable=True),
    sa.Column('information', sa.String(length=100), nullable=True),
    sa.Column('pci', sa.String(length=100), nullable=True),
    sa.Column('tableState', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('os_information')
    # ### end Alembic commands ###
