"""empty message

Revision ID: 5ed796570d61
Revises: 58ea65650dd0
Create Date: 2019-09-04 14:20:20.184611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ed796570d61'
down_revision = '58ea65650dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('os_information', sa.Column('ping', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('os_information', 'ping')
    # ### end Alembic commands ###
